# ========== Install Display Manager (greetd) ==========
# Display Manager is responsible for displaying the desktop environment.
# I use greetd + regreet for a minimal display manager.

version = 1
description = "Display manager (greetd)"

[[packages]]
names = ["greetd", "greetd-gtkgreet"]

[[symlink]]
source = "dotfiles/greetd"
target = "/etc/greetd"

[[symlink]]
source = "dotfiles/greetd/bin/archx-hyprland"
target = "/usr/local/bin/archx-hyprland"

[[symlink]]
source = "dotfiles/greetd/bin/archx-hyprland-logs"
target = "/usr/local/bin/archx-hyprland-logs"

[[symlink]]
source = "dotfiles/archx/wallpaper"
target = "/etc/archx/greeter/wallpaper"

[[service]]
name = "greetd.service"
